### PR TITLE
fix : previous/next buttons are shifted in time

### PR DESCRIPTION
**Pull request by AmazingBeu**
Description of the issue/feature this PR addresses:
remove iso weeknum conversion and use the provided weeknum to define next/previous week number.

This is due to the "datetime.strptime" function that does not support the ISO weeknum conversion before python 3.6

Current behavior before PR:
The previous and next buttons are shifted in time (#35)

Desired behavior after PR is merged:
Make buttons work again :)

### CODE REVIEW

**Comment by tonioo** [comment]
@AmazingBeu Looks like your PR fails with Python 3.4...

**Comment by AmazingBeu** [comment]
Hum... I don't think the problem comes from my PR

The failure seems to come from the setup of the database but I havn't touched that, just the functions of previous/next week buttons of the webui

Can you try running a new build from your master branch to see if this is not due to python dependencies?

**Comment by tonioo** [comment]
@AmazingBeu Indeed, might be a mysqlclient library version issue. Can you modify the requirements.txt file as follows: https://github.com/modoboa/modoboa-imap-migration/blob/master/test-requirements.txt#L4?

**Comment by AmazingBeu** [comment]
Looks like it works

**Comment by tonioo** [comment]
@AmazingBeu Yes, but the coverage is not good. Could you please add some unit tests in order to maintain the coverage level?

**Comment by tonioo** [comment]
@AmazingBeu Would you have time to finish this?

**Comment by tonioo** [comment]
@AmazingBeu Thank you.

**Pull request merged**
